### ISSUE TITLE
Gendre filter 

### ISSUE THREAD

**Issue by fahricigdem** [hahusahin/react-movie-finder#1]
Filter results with gendre and year. 

Clear Search ün Yanına bir tane daha buton. Filter results diye. Tıklayınca altta iki tane input ortaya cıkacak . Biri gendre biri yıl. Buralara değer girmezsek filtre olmayacak yani bütün yıllar ve bütün tip filmler olacak. Her yıl girilirse 2010’dan sonraki filmler gösterilecek. Diğer filtre içinde sadece macera filmleri mesela çıkacak.

**Comment by hahusahin** [comment]
Good idea buddy, I've added this feature

**Comment by fahricigdem** [comment]
super
